### ISSUE TITLE
`data_files` vs `package_data`

### ISSUE THREAD

**Issue by vidartf** [jupyter/jupyter-packaging#11]
I see that the current code updates `data_files` with the static files generated, and not `package_data`. What is the reasoning behind this? I also see that jupyterlab has a pretty neat solution for updating `package_data`:

```python
def update_package_data(distribution):
    """update build_py options to get package_data changes"""
    build_py = distribution.get_command_obj('build_py')
    build_py.finalize_options()
```

Would it be a decent (i.e. general) fix to add a call to such a function at the end of `WrappedCommand.run()`?

**Comment by blink1073** [comment]
I honestly don't remember, I was trying to fuze code from a few different code bases.  Adding that sounds good.

**Comment by SylvainCorlay** [comment]
The reason behind using `data_files` is that the proper location for static assets is absolutely under `PREFIX/share/jupyter`, i.e. located w.r.t. the prefix, which package_data is located under `site-packages`, i.e w.r.t. the location of the python files.

**Comment by SylvainCorlay** [comment]
So anything that goes under prefix configuration directory (etc) or assets (share) is a good match for wheels `data_file`. Package data is better suited when you have a resource that is only meant to be used from the python code of your package.

**Comment by vidartf** [comment]
Sure, I get that `data_files` need to be updated, I just figured that `package_data` should be updated as well :)

**Comment by vidartf** [comment]
C.f. #12.

**Comment by SylvainCorlay** [comment]
Ah ok :)

**Comment by minrk** [comment]
data_files don't arrive in a reliable destination and their destination is not recorded at install time, so you shouldn't use them if you expect *any* Python code to be able to find your data_files, unless you are dictating a small subset of supported Python install patterns. That's why package_data is generally used in Python instead of data_files. data_files work fine if 100% of installs are in conda envs and virtualenvs, but data_files can't be found reliably across platforms for `--user` or `--root` or system-wide installs in many common cases.

package_data is a crutch in Python packages because data_files are inherently unreliable. It's generally used for things like documentation, but should be avoided for things like assets actually used by any code, such as static js.

ipykernel recently started installing its own kernelspec in data_files, which is great because it works in most cases. But any code that relies on the files that end up in data_files needs to have a runtime install mechanism like `ipython kernel install` to handle the cases where data_files didn't go where you need them.
