### ISSUE TITLE
Remove data_files on uninstall

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-packaging#38]
In #35 we added a [develop_handler](https://github.com/jupyter/jupyter-packaging/blob/21dc6f7bf93ea0de05e57e226a3072c0b110e492/jupyter_packaging/setupbase.py#L167) to handle `data_files` for a `develop` install.

Currently we do not remove `data_files` during an `uninstall`.   `uninstall` is an option given to the `develop` [target](https://github.com/pypa/setuptools/blob/91213fb2e7eecde9f5d7582de485398f546e7aa8/setuptools/command/develop.py#L28).  We can use the presence of that option to remove those files.

**Comment by blink1073** [comment]
I think we should release 1.0 after this is fixed.

**Comment by vidartf** [comment]
We can override the `uninstall_link` method to add the logic, but there isn't really a *robust* way to get a list of the files that were copied over during the `develop` step. Some "best-efforts" options could be:
1. Run a build step during uninstall, and delete any files that would be included in from this.
2. Add some data to the egg-info during the develop step, and remove them during the uninstall step.

Systemic problem cases:
- If the filenames generated include a random or changing part (uuid, date, version, etc.), then 1. will fail to clean these up.
- If the datafile spec or content changes, then 1. will fail to clean these up
- If the package is develop installed into multiple environments, the egg-info might be incorrect for the current uninstall, so 2. might fail to clean up some files. I'm wondering if might be impossible to use a folder for multiple dev installs reliably though, so this might be declared as out of scope.
- If the developer does a `git clean -xdf`, or otherwise deletes the egg-info folder, 2. will always fail.

Hopefully someone has a smarter idea or I'm missing an opportunity in the build system?
